# Generated by Django 5.2.5 on 2025-08-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=23)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=100)),
            ],
        ),
    ]
